services:
  web:
    image: nas415/lead_crafter:latest
    env_file:
      - .env
    command: >
      sh -c "
        python3.10 manage.py makemigrations &&
        python3.10 manage.py migrate &&
        python3.10 manage.py runserver 0.0.0.0:7759
      "
    volumes:
      - .:/app
    ports:
      - "7759:7759"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres

  db:
    image: postgres:14
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

volumes:
  postgres_data:
